steps:
  - name: 'golang:1.19'
    entrypoint: 'bash'
    args:
    - '-eEuo'
    - 'pipefail'
    - '-c'
    - |-
      apt-get update && apt-get install -y unzip build-essential && ls && make VERSION=$TAG_NAME release-linux

  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
    - '-eEuo'
    - 'pipefail'
    - '-c'
    - |-
      ls . && ls ./dist
  - name: "gcr.io/cloud-builders/gsutil"
    args:
      [
        "cp",
        "./dist/geotemporal-data-explorer-linux-amd64-$TAG_NAME",
        "gs://geotemporal-data-explorer-releases/versions/geotemporal-data-explorer-linux-amd64-$TAG_NAME"
      ]
  - name: "gcr.io/cloud-builders/gsutil"
    args:
      [
        "cp",
        "./dist/geotemporal-data-explorer-linux-amd64-$TAG_NAME",
        "gs://geotemporal-data-explorer-releases/versions/geotemporal-data-explorer-linux-amd64-latest"
      ]
  - name: "gcr.io/cloud-builders/gsutil"
    args:
      [
        "cp",
        "./scripts/install.sh",
        "gs://geotemporal-data-explorer-releases/install.sh"
      ]


timeout: 900s